### ISSUE TITLE
English translation for the app

### ISSUE THREAD

**Issue by ljgp6** [WaifuPX-DG/WaifuPX#2]
Any english translation of the app please? Thank you

**Comment by ljgp6** [comment]
Done https://github.com/WaifuPX-DG/WaifuPX/releases/tag/5.9

**Comment by dg-encrypt** [comment]
👍😸

**Comment by WaifuPX-DG** [comment]
😸👍

**Comment by WaifuPX-DG** [comment]
> Done https://github.com/WaifuPX-DG/WaifuPX/releases/tag/5.9

😸👍
